/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.diveinsoft.blog.headers.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param email 
 * @param phone 
 * @param address 
 * @param city 
 * @param state 
 * @param zip 
 * @param country 
 */


data class Customer (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("phone")
    val phone: kotlin.String? = null,

    @SerializedName("address")
    val address: kotlin.String? = null,

    @SerializedName("city")
    val city: kotlin.String? = null,

    @SerializedName("state")
    val state: kotlin.String? = null,

    @SerializedName("zip")
    val zip: kotlin.String? = null,

    @SerializedName("country")
    val country: kotlin.String? = null

)

