/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.diveinsoft.blog.headers.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param customerId 
 * @param dateOrdered 
 * @param status 
 * @param totalPrice 
 * @param totalAmount 
 * @param totalTax 
 * @param totalDiscount 
 * @param taxRate 
 */


data class Order (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("customerId")
    val customerId: kotlin.Long? = null,

    @SerializedName("dateOrdered")
    val dateOrdered: java.time.OffsetDateTime? = null,

    @SerializedName("status")
    val status: kotlin.String? = null,

    @SerializedName("totalPrice")
    val totalPrice: kotlin.Double? = null,

    @SerializedName("totalAmount")
    val totalAmount: kotlin.Double? = null,

    @SerializedName("totalTax")
    val totalTax: kotlin.Double? = null,

    @SerializedName("totalDiscount")
    val totalDiscount: kotlin.Double? = null,

    @SerializedName("taxRate")
    val taxRate: kotlin.Double? = null

)

