/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.diveinsoft.blog.headers.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param type 
 * @param title 
 * @param fullText 
 * @param discount 
 * @param imageUrl 
 * @param startDate 
 * @param endDate 
 * @param code 
 */


data class Promotion (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("type")
    val type: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("fullText")
    val fullText: kotlin.String? = null,

    @SerializedName("discount")
    val discount: kotlin.Double? = null,

    @SerializedName("imageUrl")
    val imageUrl: kotlin.String? = null,

    @SerializedName("startDate")
    val startDate: java.time.OffsetDateTime? = null,

    @SerializedName("endDate")
    val endDate: java.time.OffsetDateTime? = null,

    @SerializedName("code")
    val code: kotlin.String? = null

)

